# 数据配置
data:
  base_url: "https://sdt-api.ok-skins.com"
  output_dir: "data/kline"
  processed_dir: "data/processed"

# 请求配置
request:
  headers:
    accept: "*/*"
    accept-encoding: "gzip, deflate, br, zstd"
    accept-language: "zh-CN,zh;q=0.9"
    access-token: "undefined"
    language: "zh_CN"
    origin: "https://steamdt.com"
    referer: "https://steamdt.com/"
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
    x-app-version: "1.0.0"
    x-currency: "CNY"
    x-device: "1"
    x-device-id: "0fdc1236-31ee-464b-bb73-a33616b068c2"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

llm_api:
  api_url: "https://api.siliconflow.cn/v1/chat/completions"
  model: "Qwen/QwQ-32B"
  max_tokens: 1024
  temperature: 0.7
  top_p: 0.7
